In [1]:
import pandas as pd

## Pandas version

In [2]:
pd.__version__

'3.0.0'

## Records count

In [6]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")
len(df)

10000

## Fuel types

In [7]:
df["fuel_type"].value_counts()

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

## Missing values

In [8]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

## Max fuel efficiency

In [9]:
df.describe().round(2)

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.00,10000.00,10000.00,10000.00,9123.00,10000.00,9736.00,10000.00
mean,1999.55,3.50,2268.81,6.04,254.45,4286.75,18.89,30.00
std,14.21,0.95,183.45,0.54,22.84,266.21,1.28,2.93
min,1975.00,2.00,1590.00,4.00,171.00,3320.00,14.00,19.80
25%,1987.00,3.00,2150.00,6.00,239.00,4110.00,18.00,28.00
50%,2000.00,4.00,2270.00,6.00,254.00,4280.00,18.90,30.00
75%,2012.00,4.00,2390.00,6.00,270.00,4470.00,19.70,31.90
max,2024.00,5.00,3110.00,8.00,334.00,5460.00,23.80,41.20

## Median value of horsepower

In [14]:
median = df["horsepower"].median()
mode = df["horsepower"].mode()

print("median: ", median)
print("mode: ", mode)

median:  254.0
mode:  0    252.0
Name: horsepower, dtype: float64

In [16]:
df["horsepower"] = df["horsepower"].fillna(252.0)

In [17]:
df["horsepower"].median()

np.float64(252.0)

## Sum of weights

In [22]:
asiatic_cars = df[df["origin"]=="Asia"][["vehicle_weight", "model_year"]]

In [24]:
asiatic_cars.head(7)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

In [26]:
X = asiatic_cars.head(7).to_numpy()

In [33]:
import numpy as np
XTX = X.T.dot(X)
XTX_inv = np.linalg.inv(XTX)

In [32]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [34]:
w = XTX_inv.dot(X.T).dot(y)

In [36]:
w.sum()

np.float64(0.36919696904927746)